### ISSUE TITLE
Improve interpolation

### ISSUE THREAD

**Issue by SourenP** [SourenP/ungroup_game#115]
Interpolation is not great right now...

I've had to disable replay in #114 because it was making things worse. Worth investigating if it's not coded properly.

https://github.com/SourenP/ungroup_game/blob/d157d4a03d529cb0546f1492fc8f9fcc5bcc55c5/src/common/util/game_settings.hpp#L14

I think we are currently doing "Dead Reckoning" (+Replay if we turn it on), but instead maybe we should do "Entity interpolation". See https://www.gabrielgambetta.com/entity-interpolation.html
With "Entity Interpolation" we would be lerping towards the game state instead of applying it outright. That way we smoothly transition into the true state.

Don't forget to read up on the networking links in the readme 😄

**Comment by copacetic** [comment]
Can you describe what specific issues you're seeing with interpolation currently and what the preferred behavior would be?

**Comment by SourenP** [comment]
There seems to be jitter with the current implementation of rewind+replay (ebb06c7b731c8717af3edf81d08b1c5d9923cc18)
