### ISSUE TITLE
Improve player movement

### ISSUE THREAD

**Issue by SourenP** [SourenP/ungroup_game#8]
Can't move diagonally currently

**Comment by copacetic** [comment]
not sure how youd move diagonally with keyboard only, usually its done w mouse

**Comment by SourenP** [comment]
Also we probably want the circle to not be able to stop moving
This is currently possible by pressing a non arrow key button i think

**Comment by SourenP** [comment]
#88 improves the feel by making the player set the target velocity which the group lerps towards over time (fairly quickly). Still doesn't feel very natural when bumping into a mine though because the player can _very_ quickly reverse the "bounce off velocity" caused by the collision with the mine.
